// Copyright 2026 Maphy Technologies
// SPDX-License-Identifier: Apache-2.0

// Runtime backend tests (GS-026, GS-027, GS-028): every fixed-function and
// shader-model 1-3 program lowers through the one WGSL emitter into a complete
// WebGPU pipeline description, the WebGL2 fallback reuses the same program and
// names anything above its floor, the compatibility mode catches out-of-subset
// WGSL at emit, and the pipeline cache is content-addressed. Rendering on a
// live adapter stays the red half of these item.

import assert from "node:assert/strict";
import { test } from "node:test";
import { generateFixedFunction, generateProjectiveTexgen, parseD3d9PixelShader } from "../lib/shader.mjs";
import { createPipelineCache, describePipeline } from "../lib/graphics.mjs";

function assemblePixelShader(model, instructions) {
  const token = [0xffff0000 | model];
  for (const [opcode, operands] of instructions) {
    token.push(opcode & 0xffff);
    for (const operand of operands) token.push(operand);
  }
  token.push(0x0000ffff);
  return new Uint8Array(Uint32Array.from(token).buffer);
}

const destTemp = (index) => (0 << 28) | index;
const srcConstant = (index) => (2 << 28) | index;

function fixtureProgram() {
  return [
    { name: "ffp-lit", program: generateFixedFunction({ light_count: 2, texture_stage_count: 2, fog: true, alpha_blend: true }).program },
    { name: "ffp-plain", program: generateFixedFunction({ texture_stage_count: 1 }).program },
    { name: "texgen", program: generateProjectiveTexgen({ mode: "spotlight_cookie" }).program },
    { name: "sm2", program: parseD3d9PixelShader(assemblePixelShader(0x0200, [[1, [destTemp(0), srcConstant(0)]], [5, [destTemp(1), destTemp(0), srcConstant(1)]]])).program },
    { name: "sm3", program: parseD3d9PixelShader(assemblePixelShader(0x0300, [[2, [destTemp(0), srcConstant(0), srcConstant(1)]]])).program },
  ];
}

test("every FFP and SM1-3 fixture lowers through the one emitter into a WebGPU pipeline description", () => {
  for (const { name, program } of fixtureProgram()) {
    const description = describePipeline(program, { backend: "webgpu" });
    assert.equal(description.backend, "webgpu", name);
    assert.equal(description.shader_language, "wgsl", name);
    assert.match(description.shader_source, /generated by the single unified-representation emitter/, name);
    assert.equal(description.within_floor, true, name);
    assert.equal(description.is_live_render, false, name);
    assert.ok(Array.isArray(description.bind_group_layout), name);
  }
});

test("the color target carries the requested gamma encoding and multisample count", () => {
  const program = generateFixedFunction({ texture_stage_count: 1 }).program;
  const srgb = describePipeline(program, { gamma: "srgb", sample_count: 4 });
  assert.equal(srgb.color_target.format, "rgba8unorm-srgb");
  assert.equal(srgb.color_target.gamma, "srgb");
  assert.equal(srgb.sample_count, 4);
  const linear = describePipeline(program, {});
  assert.equal(linear.color_target.format, "rgba8unorm");
  assert.throws(() => describePipeline(program, { sample_count: 3 }), (error) => error.input_code === "invalid_sample_count");
  assert.throws(() => describePipeline(program, { backend: "vulkan" }), (error) => error.input_code === "unsupported_backend");
});

test("the WebGL2 fallback reuses the same program and emits GLSL ES 3.0", () => {
  const program = generateFixedFunction({ light_count: 1, texture_stage_count: 1 }).program;
  const description = describePipeline(program, { backend: "webgl2" });
  assert.equal(description.shader_language, "glsl-es-3.0");
  assert.match(description.shader_source, /#version 300 es/);
  assert.equal(description.within_floor, true);
  assert.deepEqual(description.above_floor_op, []);
});

test("the WebGL2 fallback names an op above the GLSL ES 3.0 floor rather than dropping it", () => {
  const program = [{ op: "lit", dest: { type: "temp", index: 0 }, dest_mask: "xyzw", src: [{ type: "constant", index: 0, swizzle: "" }] }];
  const description = describePipeline(program, { backend: "webgl2" });
  assert.deepEqual(description.above_floor_op, ["lit"]);
  assert.equal(description.within_floor, false);
  assert.match(description.shader_source, /named-blocked/);
});

test("the compatibility backend catches out-of-subset WGSL at emit", () => {
  const program = generateFixedFunction({ texture_stage_count: 1 }).program;
  assert.doesNotThrow(() => describePipeline(program, { backend: "compatibility" }));
  const description = describePipeline(program, { backend: "compatibility" });
  assert.equal(description.backend, "compatibility");
  assert.equal(description.shader_language, "wgsl");
});

test("the pipeline cache is content-addressed and API-blind", () => {
  const cache = createPipelineCache();
  const left = generateFixedFunction({ texture_stage_count: 2, light_count: 1, api: "d3d9" }).program;
  const right = generateFixedFunction({ texture_stage_count: 2, light_count: 1, api: "opengl" }).program;
  const first = cache.get(left, { backend: "webgpu" });
  assert.equal(first.hit, false);
  const second = cache.get(right, { backend: "webgpu" });
  assert.equal(second.hit, true, "identical cross-API programs share one entry");
  assert.equal(cache.size, 1);
  const other = cache.get(left, { backend: "webgl2" });
  assert.equal(other.hit, false);
  assert.equal(cache.size, 2);
});
