// Copyright 2026 Maphy Technologies
// SPDX-License-Identifier: Apache-2.0

// Graphics unification tests (GS-018, GS-020, GS-022, GS-024, GS-025): the
// Direct3D 9 pixel-shader frontend lowers into the one unified representation,
// the single emitter is deterministic, the fixed-function generator is
// API-blind, the capability report cannot exceed support, and the frame-diff
// computes its reference at test time with no committed baseline.

import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  assertCapsWithinSupport,
  computeFrameDiff,
  declaredCaps,
  emitWgsl,
  evaluateProgram,
  formatProgram,
  generateFixedFunction,
  generateProjectiveTexgen,
  generateReferenceFrame,
  parseD3d9PixelShader,
  referenceProjectiveTexgenFrame,
  renderProjectiveTexgenFrame,
} from "../lib/shader.mjs";

function assemblePixelShader(model, instructions) {
  const token = [];
  token.push(0xffff0000 | model);
  for (const [opcode, operands] of instructions) {
    token.push(opcode & 0xffff);
    for (const operand of operands) token.push(operand);
  }
  token.push(0x0000ffff);
  return Uint32Array.from(token);
}

const destTemp = (index) => (0 << 28) | index;
const srcConstant = (index) => (2 << 28) | index;

test("a pixel shader 2.0 arithmetic stream lowers into the unified representation", () => {
  const byte = assemblePixelShader(0x0200, [
    [1, [destTemp(0), srcConstant(0)]],
    [5, [destTemp(1), destTemp(0), srcConstant(1)]],
  ]);
  const program = parseD3d9PixelShader(new Uint8Array(byte.buffer));
  assert.equal(program.model, "2.0");
  const text = formatProgram(program.program);
  assert.deepEqual(text, ["mov r0, c0", "mul r1, r0, c1"]);
  const wgsl = emitWgsl(program.program);
  assert.match(wgsl, /generated by the single unified-representation emitter/);
  assert.match(wgsl, /r0/);
});

test("an unsupported opcode is named, never dropped", () => {
  const byte = assemblePixelShader(0x0200, [[99, [destTemp(0), srcConstant(0)]]]);
  assert.throws(() => parseD3d9PixelShader(new Uint8Array(byte.buffer)), (error) => {
    assert.equal(error.input_code, "unsupported_opcode");
    assert.match(error.message, /Opcode 99/);
    return true;
  });
});

test("a vertex byte stream and an above-support model are refused", () => {
  const vertex = new Uint8Array(Uint32Array.from([0xfffe0200, 0x0000ffff]).buffer);
  assert.throws(() => parseD3d9PixelShader(vertex), (error) => error.input_code === "unsupported_shader_type");
  const future = assemblePixelShader(0x0400, []);
  assert.throws(() => parseD3d9PixelShader(new Uint8Array(future.buffer)), (error) => error.input_code === "unsupported_shader_model");
  const modern = parseD3d9PixelShader(new Uint8Array(assemblePixelShader(0x0300, [[1, [destTemp(0), srcConstant(0)]]]).buffer));
  assert.equal(modern.model, "3.0");
});

test("the capability report derives from support and cannot exceed it", () => {
  const caps = declaredCaps();
  assert.equal(caps.advertised_pixel_shader_model, caps.translator_support.pixel_shader_model);
  assert.equal(caps.is_within_support, true);
  assert.doesNotThrow(() => assertCapsWithinSupport("3.0"));
  assert.throws(() => assertCapsWithinSupport("4.0"), (error) => error.input_code === "caps_exceed_support");
});

test("one fixed-function generator is API-blind: identical state yields identical output", () => {
  const state = { texture_stage_count: 2, light_count: 1, fog: true, alpha_blend: true };
  const left = generateFixedFunction({ ...state, api: "d3d9" });
  const right = generateFixedFunction({ ...state, api: "opengl" });
  assert.deepEqual(formatProgram(left.program), formatProgram(right.program));
  const withoutFog = generateFixedFunction({ ...state, fog: false });
  assert.notDeepEqual(formatProgram(left.program), formatProgram(withoutFog.program));
  const wgslLeft = emitWgsl(left.program);
  const wgslRight = emitWgsl(right.program);
  assert.equal(wgslLeft, wgslRight);
});

test("the numeric evaluator runs one program and performs the projective divide", () => {
  const program = [
    { op: "mov", dest: { type: "temp", index: 0 }, dest_mask: "xyzw", src: [{ type: "constant", index: 0, swizzle: "" }] },
    { op: "div", dest: { type: "temp", index: 1 }, dest_mask: "xy", src: [{ type: "temp", index: 0, swizzle: "xy" }, { type: "temp", index: 0, swizzle: "w" }] },
  ];
  const file = evaluateProgram(program, { constant: { 0: [4, 8, 0, 2] } });
  assert.deepEqual(file.temp[1].slice(0, 2), [2, 4]);
});

test("the projective texgen generator is API-blind and lowers through the one emitter", () => {
  const state = { mode: "spotlight_cookie", texture_stage_count: 1 };
  const d3d = generateProjectiveTexgen({ ...state, api: "d3d9" });
  const gl = generateProjectiveTexgen({ ...state, api: "opengl" });
  assert.deepEqual(formatProgram(d3d.program), formatProgram(gl.program));
  assert.equal(d3d.has_projection_divide, true);
  assert.match(emitWgsl(d3d.program), /\//);
  assert.throws(() => generateProjectiveTexgen({ mode: "bogus" }), (error) => error.input_code === "unsupported_texgen_mode");
});

test("the spotlight-cookie and planar-shadow fixtures render within tolerance and the dropped divide fails closed", () => {
  const matrix = [
    [0.5, 0, 0, 0.5],
    [0, 0.5, 0, 0.5],
    [0, 0, 1, 0],
    [0, 0, 0, 2],
  ];
  const scene = {
    matrix,
    vertex: [
      [0.4, 0.4, 0, 1],
      [-0.2, 0.3, 0, 1],
      [0.6, -0.5, 0, 1],
      [0.1, 0.1, 0, 1],
    ],
  };
  for (const mode of ["spotlight_cookie", "planar_shadow"]) {
    const reference = referenceProjectiveTexgenFrame(scene);
    const rendered = renderProjectiveTexgenFrame({ mode }, scene);
    const report = computeFrameDiff(rendered, reference, { mean_tolerance: 1.0, reference_source: "projective oracle computed at test time" });
    assert.equal(report.pass, true, `${mode} must render within tolerance`);
    assert.equal(report.committed_baseline, false);
    const mutated = renderProjectiveTexgenFrame({ mode, drop_projection_divide: true }, scene);
    const mutatedReport = computeFrameDiff(mutated, reference, { mean_tolerance: 1.0 });
    assert.equal(mutatedReport.pass, false, `${mode} with the projection divide dropped must fail closed`);
  }
});

test("the frame diff computes its reference at test time with no committed baseline", (context) => {
  const fixture = mkdtempSync(join(tmpdir(), "bptk-framediff-"));
  context.after(() => rmSync(fixture, { recursive: true, force: true }));
  const reference = generateReferenceFrame(4, 4, [128, 128, 128]);
  const rendered = generateReferenceFrame(4, 4, [130, 126, 128]);
  const report = computeFrameDiff(rendered, reference, { reference_source: "computed at test time in the suite" });
  assert.equal(report.pass, true);
  assert.equal(report.committed_baseline, false);
  const drifted = generateReferenceFrame(4, 4, [255, 0, 0]);
  const failed = computeFrameDiff(drifted, reference);
  assert.equal(failed.pass, false);
  assert.throws(() => computeFrameDiff([0, 0, 0], reference), (error) => error.input_code === "frame_length_mismatch");
});
